'use strict';

const Countries = Object.freeze([
  {
    code: "SG",
    name_en: "SINGAPORE",
    dial_code: "+65",
    name_zh: "新加坡",
    key: "Singapore",
    iso_code_3: "SGP",
  },
  {
    code: "CN",
    name_en: "CHINA",
    dial_code: "+86",
    name_zh: "中国",
    key: "China",
    iso_code_3: "CHN",
  },
  {
    code: "HK",
    name_en: "HONG KONG",
    dial_code: "+852",
    name_zh: "香港",
    key: "Hong Kong",
    iso_code_3: "HKG",
  },
  {
    code: "MY",
    name_en: "MALAYSIA",
    dial_code: "+60",
    name_zh: "马来西亚",
    key: "Malaysia",
    iso_code_3: "MYS",
  },
  {
    code: "ID",
    name_en: "INDONESIA",
    dial_code: "+62",
    name_zh: "印度尼西亚",
    key: "Indonesia",
    iso_code_3: "IDN",
  },
  {
    code: "GB",
    name_en: "UNITED KINGDOM",
    dial_code: "+44",
    name_zh: "英国",
    key: "United Kingdom",
    iso_code_3: "GBR",
  },
  {
    code: "US",
    name_en: "UNITED STATES OF AMERICA",
    dial_code: "+1",
    name_zh: "美国",
    key: "United States of America",
    iso_code_3: "USA",
  },
  {
    code: "AF",
    name_en: "AFGHANISTAN",
    dial_code: "+93",
    name_zh: "阿富汗",
    key: "Afghanistan",
    iso_code_3: "AFG",
  },
  {
    code: "AX",
    name_en: "ALAND ISLANDS",
    dial_code: "+358",
    name_zh: "奥兰群岛",
    key: "Aland Islands",
    iso_code_3: "ALA",
  },
  {
    code: "AL",
    name_en: "ALBANIA",
    dial_code: "+355",
    name_zh: "阿尔巴尼亚",
    key: "Albania",
    iso_code_3: "ALB",
  },
  {
    code: "DZ",
    name_en: "ALGERIA",
    dial_code: "+213",
    name_zh: "阿尔及利亚",
    key: "Algeria",
    iso_code_3: "DZA",
  },
  {
    code: "AS",
    name_en: "AMERICAN SAMOA",
    dial_code: "+1684",
    name_zh: "美属萨摩亚",
    key: "American Samoa",
    iso_code_3: "ASM",
  },
  {
    code: "AD",
    name_en: "ANDORRA",
    dial_code: "+376",
    name_zh: "安道尔",
    key: "Andorra",
    iso_code_3: "AND",
  },
  {
    code: "AO",
    name_en: "ANGOLA",
    dial_code: "+244",
    name_zh: "安哥拉",
    key: "Angola",
    iso_code_3: "AGO",
  },
  {
    code: "AI",
    name_en: "ANGUILLA",
    dial_code: "+1264",
    name_zh: "安圭拉",
    key: "Anguilla",
    iso_code_3: "AIA",
  },
  {
    code: "AQ",
    name_en: "ANTARCTICA",
    dial_code: "+672",
    name_zh: "南极洲",
    key: "Antarctica",
    iso_code_3: "ATA",
  },
  {
    code: "AG",
    name_en: "ANTIGUA AND BARBUDA",
    dial_code: "+1268",
    name_zh: "安提瓜和巴布达",
    key: "Antigua and Barbuda",
    iso_code_3: "ATG",
  },
  {
    code: "AR",
    name_en: "ARGENTINA",
    dial_code: "+54",
    name_zh: "阿根廷",
    key: "Argentina",
    iso_code_3: "ARG",
  },
  {
    code: "AM",
    name_en: "ARMENIA",
    dial_code: "+374",
    name_zh: "亚美尼亚",
    key: "Armenia",
    iso_code_3: "ARM",
  },
  {
    code: "AW",
    name_en: "ARUBA",
    dial_code: "+297",
    name_zh: "阿鲁巴",
    key: "Aruba",
    iso_code_3: "ABW",
  },
  {
    code: "AU",
    name_en: "AUSTRALIA",
    dial_code: "+61",
    name_zh: "澳大利亚",
    key: "Australia",
    iso_code_3: "AUS",
  },
  {
    code: "AT",
    name_en: "AUSTRIA",
    dial_code: "+43",
    name_zh: "奥地利",
    key: "Austria",
    iso_code_3: "AUT",
  },
  {
    code: "AZ",
    name_en: "AZERBAIJAN",
    dial_code: "+994",
    name_zh: "阿塞拜疆",
    key: "Azerbaijan",
    iso_code_3: "AZE",
  },
  {
    code: "BS",
    name_en: "BAHAMAS",
    dial_code: "+1242",
    name_zh: "巴哈马",
    key: "Bahamas",
    iso_code_3: "BHS",
  },
  {
    code: "BH",
    name_en: "BAHRAIN",
    dial_code: "+973",
    name_zh: "巴林",
    key: "Bahrain",
    iso_code_3: "BHR",
  },
  {
    code: "BD",
    name_en: "BANGLADESH",
    dial_code: "+880",
    name_zh: "孟加拉国",
    key: "Bangladesh",
    iso_code_3: "BGD",
  },
  {
    code: "BB",
    name_en: "BARBADOS",
    dial_code: "+1246",
    name_zh: "巴巴多斯",
    key: "Barbados",
    iso_code_3: "BRB",
  },
  {
    code: "BY",
    name_en: "BELARUS",
    dial_code: "+375",
    name_zh: "白俄罗斯",
    key: "Belarus",
    iso_code_3: "BLR",
  },
  {
    code: "BE",
    name_en: "BELGIUM",
    dial_code: "+32",
    name_zh: "比利时",
    key: "Belgium",
    iso_code_3: "BEL",
  },
  {
    code: "BZ",
    name_en: "BELIZE",
    dial_code: "+501",
    name_zh: "伯利兹",
    key: "Belize",
    iso_code_3: "BLZ",
  },
  {
    code: "BJ",
    name_en: "BENIN",
    dial_code: "+229",
    name_zh: "贝宁",
    key: "Benin",
    iso_code_3: "BEN",
  },
  {
    code: "BM",
    name_en: "BERMUDA",
    dial_code: "+1441",
    name_zh: "百慕大",
    key: "Bermuda",
    iso_code_3: "BMU",
  },
  {
    code: "BT",
    name_en: "BHUTAN",
    dial_code: "+975",
    name_zh: "不丹",
    key: "Bhutan",
    iso_code_3: "BTN",
  },
  {
    code: "BO",
    name_en: "BOLIVIA",
    dial_code: "+591",
    name_zh: "玻利维亚",
    key: "Bolivia",
    iso_code_3: "BOL",
  },
  {
    code: "BA",
    name_en: "BOSNIA AND HERZEGOVINA",
    dial_code: "+387",
    name_zh: "波斯尼亚和黑塞哥维那",
    key: "Bosnia and Herzegovina",
    iso_code_3: "BIH",
  },
  {
    code: "BW",
    name_en: "BOTSWANA",
    dial_code: "+267",
    name_zh: "博茨瓦纳",
    key: "Botswana",
    iso_code_3: "BWA",
  },
  {
    code: "BV",
    name_en: "BOUVET ISLAND",
    dial_code: "+55",
    name_zh: "布维岛",
    key: "Bouvet Island",
    iso_code_3: "BVT",
  },
  {
    code: "BR",
    name_en: "BRAZIL",
    dial_code: "+55",
    name_zh: "巴西",
    key: "Brazil",
    iso_code_3: "BRA",
  },
  {
    code: "IO",
    name_en: "BRITISH INDIAN OCEAN TERRITORY",
    dial_code: "+246",
    name_zh: "英属印度洋领地",
    key: "British Indian Ocean Territory",
    iso_code_3: "IOT",
  },
  {
    code: "BN",
    name_en: "BRUNEI",
    dial_code: "+673",
    name_zh: "文莱",
    key: "Brunei",
    iso_code_3: "BRN",
  },
  {
    code: "BG",
    name_en: "BULGARIA",
    dial_code: "+359",
    name_zh: "保加利亚",
    key: "Bulgaria",
    iso_code_3: "BGR",
  },
  {
    code: "BF",
    name_en: "BURKINA FASO",
    dial_code: "+226",
    name_zh: "布基纳法索",
    key: "Burkina Faso",
    iso_code_3: "BFA",
  },
  {
    code: "BI",
    name_en: "BURUNDI",
    dial_code: "+257",
    name_zh: "布隆迪",
    key: "Burundi",
    iso_code_3: "BDI",
  },
  {
    code: "KH",
    name_en: "CAMBODIA",
    dial_code: "+855",
    name_zh: "柬埔寨",
    key: "Cambodia",
    iso_code_3: "KHM",
  },
  {
    code: "CM",
    name_en: "CAMEROON",
    dial_code: "+237",
    name_zh: "喀麦隆",
    key: "Cameroon",
    iso_code_3: "CMR",
  },
  {
    code: "CA",
    name_en: "CANADA",
    dial_code: "+1",
    name_zh: "加拿大",
    key: "Canada",
    iso_code_3: "CAN",
  },
  {
    code: "CV",
    name_en: "CAPE VERDE",
    dial_code: "+238",
    name_zh: "佛得角",
    key: "Cape Verde",
    iso_code_3: "CPV",
  },
  {
    code: "KY",
    name_en: "CAYMAN ISLANDS",
    dial_code: "+1345",
    name_zh: "开曼群岛",
    key: "Cayman Islands",
    iso_code_3: "CYM",
  },
  {
    code: "CF",
    name_en: "CENTRAL AFRICAN REPUBLIC",
    dial_code: "+236",
    name_zh: "中非共和国",
    key: "Central African Republic",
    iso_code_3: "CAF",
  },
  {
    code: "TD",
    name_en: "CHAD",
    dial_code: "+235",
    name_zh: "乍得",
    key: "Chad",
    iso_code_3: "TCD",
  },
  {
    code: "CL",
    name_en: "CHILE",
    dial_code: "+56",
    name_zh: "智利",
    key: "Chile",
    iso_code_3: "CHL",
  },
  {
    code: "CX",
    name_en: "CHRISTMAS ISLAND",
    dial_code: "+61",
    name_zh: "圣诞岛",
    key: "Christmas Island",
    iso_code_3: "CXR",
  },
  {
    code: "CC",
    name_en: "COCOS (KEELING) ISLANDS",
    dial_code: "+61",
    name_zh: "科科斯（基林）群岛",
    key: "Cocos (Keeling) Islands",
    iso_code_3: "CCK",
  },
  {
    code: "CO",
    name_en: "COLOMBIA",
    dial_code: "+57",
    name_zh: "哥伦比亚",
    key: "Colombia",
    iso_code_3: "COL",
  },
  {
    code: "KM",
    name_en: "COMOROS",
    dial_code: "+269",
    name_zh: "科摩罗",
    key: "Comoros",
    iso_code_3: "COM",
  },
  {
    code: "CG",
    name_en: "CONGO (REPUBLIC OF)",
    dial_code: "+242",
    name_zh: "刚果（共和国）",
    key: "Congo (Republic of)",
    iso_code_3: "COG",
  },
  {
    code: "CD",
    name_en: "DEMOCRATIC REPUBLIC OF THE CONGO",
    dial_code: "+243",
    name_zh: "刚果民主共和国",
    key: "Democratic Republic of the Congo",
    iso_code_3: "COD",
  },
  {
    code: "CK",
    name_en: "COOK ISLANDS",
    dial_code: "+682",
    name_zh: "库克群岛",
    key: "Cook Islands",
    iso_code_3: "COK",
  },
  {
    code: "CR",
    name_en: "COSTA RICA",
    dial_code: "+506",
    name_zh: "哥斯达黎加",
    key: "Costa Rica",
    iso_code_3: "CRI",
  },
  {
    code: "CI",
    name_en: "COTE D'IVOIRE (IVORY COAST)",
    dial_code: "+225",
    name_zh: "科特迪瓦（象牙海岸）",
    key: "Cote d'Ivoire (Ivory Coast)",
    iso_code_3: "CIV",
  },
  {
    code: "HR",
    name_en: "CROATIA",
    dial_code: "+385",
    name_zh: "克罗地亚",
    key: "Croatia",
    iso_code_3: "HRV",
  },
  {
    code: "CU",
    name_en: "CUBA",
    dial_code: "+53",
    name_zh: "古巴",
    key: "Cuba",
    iso_code_3: "CUB",
  },
  {
    code: "CW",
    name_en: "CURACAO",
    dial_code: "+5999",
    name_zh: "库拉索",
    key: "Curacao",
    iso_code_3: "CUW",
  },
  {
    code: "CY",
    name_en: "CYPRUS",
    dial_code: "+357",
    name_zh: "塞浦路斯",
    key: "Cyprus",
    iso_code_3: "CYP",
  },
  {
    code: "CZ",
    name_en: "CZECH REPUBLIC",
    dial_code: "+420",
    name_zh: "捷克共和国",
    key: "Czech Republic",
    iso_code_3: "CZE",
  },
  {
    code: "DK",
    name_en: "DENMARK",
    dial_code: "+45",
    name_zh: "丹麦",
    key: "Denmark",
    iso_code_3: "DNK",
  },
  {
    code: "DJ",
    name_en: "DJIBOUTI",
    dial_code: "+253",
    name_zh: "吉布提",
    key: "Djibouti",
    iso_code_3: "DJI",
  },
  {
    code: "DM",
    name_en: "DOMINICA",
    dial_code: "+1767",
    name_zh: "多米尼加",
    key: "Dominica",
    iso_code_3: "DMA",
  },
  {
    code: "DO",
    name_en: "DOMINICAN REPUBLIC",
    dial_code: "+1849",
    name_zh: "多明尼加共和国",
    key: "Dominican Republic",
    iso_code_3: "DOM",
  },
  {
    code: "EC",
    name_en: "ECUADOR",
    dial_code: "+593",
    name_zh: "厄瓜多尔",
    key: "Ecuador",
    iso_code_3: "ECU",
  },
  {
    code: "EG",
    name_en: "EGYPT",
    dial_code: "+20",
    name_zh: "埃及",
    key: "Egypt",
    iso_code_3: "EGY",
  },
  {
    code: "SV",
    name_en: "EL SALVADOR",
    dial_code: "+503",
    name_zh: "萨尔瓦多",
    key: "El Salvador",
    iso_code_3: "SLV",
  },
  {
    code: "GQ",
    name_en: "EQUATORIAL GUINEA",
    dial_code: "+240",
    name_zh: "赤道几内亚",
    key: "Equatorial Guinea",
    iso_code_3: "GNQ",
  },
  {
    code: "ER",
    name_en: "ERITREA",
    dial_code: "+291",
    name_zh: "厄立特里亚",
    key: "Eritrea",
    iso_code_3: "ERI",
  },
  {
    code: "EE",
    name_en: "ESTONIA",
    dial_code: "+372",
    name_zh: "爱沙尼亚",
    key: "Estonia",
    iso_code_3: "EST",
  },
  {
    code: "ET",
    name_en: "ETHIOPIA",
    dial_code: "+251",
    name_zh: "埃塞俄比亚",
    key: "Ethiopia",
    iso_code_3: "ETH",
  },
  {
    code: "FK",
    name_en: "FALKLAND ISLANDS",
    dial_code: "+500",
    name_zh: "福克兰群岛",
    key: "Falkland Islands",
    iso_code_3: "FLK",
  },
  {
    code: "FO",
    name_en: "FAROE ISLANDS",
    dial_code: "+298",
    name_zh: "法罗群岛",
    key: "Faroe Islands",
    iso_code_3: "FRO",
  },
  {
    code: "FJ",
    name_en: "FIJI",
    dial_code: "+679",
    name_zh: "斐济",
    key: "Fiji",
    iso_code_3: "FJI",
  },
  {
    code: "FI",
    name_en: "FINLAND",
    dial_code: "+358",
    name_zh: "芬兰",
    key: "Finland",
    iso_code_3: "FIN",
  },
  {
    code: "FR",
    name_en: "FRANCE",
    dial_code: "+33",
    name_zh: "法国",
    key: "France",
    iso_code_3: "FRA",
  },
  {
    code: "GF",
    name_en: "FRENCH GUIANA",
    dial_code: "+594",
    name_zh: "法属圭亚那",
    key: "French Guiana",
    iso_code_3: "GUF",
  },
  {
    code: "PF",
    name_en: "FRENCH POLYNESIA",
    dial_code: "+689",
    name_zh: "法属波利尼西亚",
    key: "French Polynesia",
    iso_code_3: "PYF",
  },
  {
    code: "GA",
    name_en: "GABON",
    dial_code: "+241",
    name_zh: "加蓬",
    key: "Gabon",
    iso_code_3: "GAB",
  },
  {
    code: "GM",
    name_en: "GAMBIA",
    dial_code: "+220",
    name_zh: "冈比亚",
    key: "Gambia",
    iso_code_3: "GMB",
  },
  {
    code: "GE",
    name_en: "GEORGIA",
    dial_code: "+995",
    name_zh: "格鲁吉亚",
    key: "Georgia",
    iso_code_3: "GEO",
  },
  {
    code: "DE",
    name_en: "GERMANY",
    dial_code: "+49",
    name_zh: "德国",
    key: "Germany",
    iso_code_3: "DEU",
  },
  {
    code: "GH",
    name_en: "GHANA",
    dial_code: "+233",
    name_zh: "加纳",
    key: "Ghana",
    iso_code_3: "GHA",
  },
  {
    code: "GI",
    name_en: "GIBRALTAR",
    dial_code: "+350",
    name_zh: "直布罗陀",
    key: "Gibraltar",
    iso_code_3: "GIB",
  },
  {
    code: "GR",
    name_en: "GREECE",
    dial_code: "+30",
    name_zh: "希腊",
    key: "Greece",
    iso_code_3: "GRC",
  },
  {
    code: "GL",
    name_en: "GREENLAND",
    dial_code: "+299",
    name_zh: "格陵兰",
    key: "Greenland",
    iso_code_3: "GRL",
  },
  {
    code: "GD",
    name_en: "GRENADA",
    dial_code: "+1473",
    name_zh: "格林纳达",
    key: "Grenada",
    iso_code_3: "GRD",
  },
  {
    code: "GP",
    name_en: "GUADELOUPE",
    dial_code: "+590",
    name_zh: "瓜德罗普岛",
    key: "Guadeloupe",
    iso_code_3: "GLP",
  },
  {
    code: "GU",
    name_en: "GUAM",
    dial_code: "+1671",
    name_zh: "关岛",
    key: "Guam",
    iso_code_3: "GUM",
  },
  {
    code: "GT",
    name_en: "GUATEMALA",
    dial_code: "+502",
    name_zh: "危地马拉",
    key: "Guatemala",
    iso_code_3: "GTM",
  },
  {
    code: "GG",
    name_en: "GUERNSEY",
    dial_code: "+44",
    name_zh: "根西岛",
    key: "Guernsey",
    iso_code_3: "GGY",
  },
  {
    code: "GN",
    name_en: "GUINEA",
    dial_code: "+224",
    name_zh: "几内亚",
    key: "Guinea",
    iso_code_3: "GIN",
  },
  {
    code: "GW",
    name_en: "GUINEA-BISSAU",
    dial_code: "+245",
    name_zh: "几内亚比绍",
    key: "Guinea-Bissau",
    iso_code_3: "GNB",
  },
  {
    code: "GY",
    name_en: "GUYANA",
    dial_code: "+592",
    name_zh: "圭亚那",
    key: "Guyana",
    iso_code_3: "GUY",
  },
  {
    code: "HT",
    name_en: "HAITI",
    dial_code: "+509",
    name_zh: "海地",
    key: "Haiti",
    iso_code_3: "HTI",
  },
  {
    code: "HM",
    name_en: "HEARD AND MCDONALD ISLANDS",
    dial_code: "+672",
    name_zh: "赫德和麦克唐纳群岛",
    key: "Heard and McDonald Islands",
    iso_code_3: "HMD",
  },
  {
    code: "VA",
    name_en: "VATICAN",
    dial_code: "+379",
    name_zh: "梵蒂冈",
    key: "Vatican",
    iso_code_3: "VAT",
  },
  {
    code: "HN",
    name_en: "HONDURAS",
    dial_code: "+504",
    name_zh: "洪都拉斯",
    key: "Honduras",
    iso_code_3: "HND",
  },
  {
    code: "HU",
    name_en: "HUNGARY",
    dial_code: "+36",
    name_zh: "匈牙利",
    key: "Hungary",
    iso_code_3: "HUN",
  },
  {
    code: "IS",
    name_en: "ICELAND",
    dial_code: "+354",
    name_zh: "冰岛",
    key: "Iceland",
    iso_code_3: "ISL",
  },
  {
    code: "IN",
    name_en: "INDIA",
    dial_code: "+91",
    name_zh: "印度",
    key: "India",
    iso_code_3: "IND",
  },
  {
    code: "IR",
    name_en: "IRAN",
    dial_code: "+98",
    name_zh: "伊朗",
    key: "Iran",
    iso_code_3: "IRN",
  },
  {
    code: "IQ",
    name_en: "IRAQ",
    dial_code: "+964",
    name_zh: "伊拉克",
    key: "Iraq",
    iso_code_3: "IRQ",
  },
  {
    code: "IE",
    name_en: "IRELAND",
    dial_code: "+353",
    name_zh: "爱尔兰",
    key: "Ireland",
    iso_code_3: "IRL",
  },
  {
    code: "IM",
    name_en: "ISLE OF MAN",
    dial_code: "+44",
    name_zh: "马恩岛",
    key: "Isle of Man",
    iso_code_3: "IMN",
  },
  {
    code: "IL",
    name_en: "ISRAEL",
    dial_code: "+972",
    name_zh: "以色列",
    key: "Israel",
    iso_code_3: "ISR",
  },
  {
    code: "IT",
    name_en: "ITALY",
    dial_code: "+39",
    name_zh: "意大利",
    key: "Italy",
    iso_code_3: "ITA",
  },
  {
    code: "JM",
    name_en: "JAMAICA",
    dial_code: "+1876",
    name_zh: "牙买加",
    key: "Jamaica",
    iso_code_3: "JAM",
  },
  {
    code: "JP",
    name_en: "JAPAN",
    dial_code: "+81",
    name_zh: "日本",
    key: "Japan",
    iso_code_3: "JPN",
  },
  {
    code: "JE",
    name_en: "JERSEY",
    dial_code: "+44",
    name_zh: "新泽西",
    key: "Jersey",
    iso_code_3: "JEY",
  },
  {
    code: "JO",
    name_en: "JORDAN",
    dial_code: "+962",
    name_zh: "约旦",
    key: "Jordan",
    iso_code_3: "JOR",
  },
  {
    code: "KZ",
    name_en: "KAZAKHSTAN",
    dial_code: "+77",
    name_zh: "哈萨克斯坦",
    key: "Kazakhstan",
    iso_code_3: "KAZ",
  },
  {
    code: "KE",
    name_en: "KENYA",
    dial_code: "+254",
    name_zh: "肯尼亚",
    key: "Kenya",
    iso_code_3: "KEN",
  },
  {
    code: "KI",
    name_en: "KIRIBATI",
    dial_code: "+686",
    name_zh: "基里巴斯",
    key: "Kiribati",
    iso_code_3: "KIR",
  },
  {
    code: "KP",
    name_en: "NORTH KOREA",
    dial_code: "+850",
    name_zh: "朝鲜",
    key: "North Korea",
    iso_code_3: "PRK",
  },
  {
    code: "KR",
    name_en: "SOUTH KOREA",
    dial_code: "+82",
    name_zh: "韩国",
    key: "South Korea",
    iso_code_3: "KOR",
  },
  {
    code: "KW",
    name_en: "KUWAIT",
    dial_code: "+965",
    name_zh: "科威特",
    key: "Kuwait",
    iso_code_3: "KWT",
  },
  {
    code: "KG",
    name_en: "KYRGYZSTAN",
    dial_code: "+996",
    name_zh: "吉尔吉斯斯坦",
    key: "Kyrgyzstan",
    iso_code_3: "KGZ",
  },
  {
    code: "LA",
    name_en: "LAOS",
    dial_code: "+856",
    name_zh: "老挝",
    key: "Laos",
    iso_code_3: "LAO",
  },
  {
    code: "LV",
    name_en: "LATVIA",
    dial_code: "+371",
    name_zh: "拉脱维亚",
    key: "Latvia",
    iso_code_3: "LVA",
  },
  {
    code: "LB",
    name_en: "LEBANON",
    dial_code: "+961",
    name_zh: "黎巴嫩",
    key: "Lebanon",
    iso_code_3: "LBN",
  },
  {
    code: "LS",
    name_en: "LESOTHO",
    dial_code: "+266",
    name_zh: "莱索托",
    key: "Lesotho",
    iso_code_3: "LSO",
  },
  {
    code: "LR",
    name_en: "LIBERIA",
    dial_code: "+231",
    name_zh: "利比里亚",
    key: "Liberia",
    iso_code_3: "LBR",
  },
  {
    code: "LY",
    name_en: "LIBYA",
    dial_code: "+218",
    name_zh: "利比亚",
    key: "Libya",
    iso_code_3: "LBY",
  },
  {
    code: "LI",
    name_en: "LIECHTENSTEIN",
    dial_code: "+423",
    name_zh: "列支敦士登",
    key: "Liechtenstein",
    iso_code_3: "LIE",
  },
  {
    code: "LT",
    name_en: "LITHUANIA",
    dial_code: "+370",
    name_zh: "立陶宛",
    key: "Lithuania",
    iso_code_3: "LTU",
  },
  {
    code: "LU",
    name_en: "LUXEMBOURG",
    dial_code: "+352",
    name_zh: "卢森堡",
    key: "Luxembourg",
    iso_code_3: "LUX",
  },
  {
    code: "MO",
    name_en: "MACAU",
    dial_code: "+853",
    name_zh: "澳门",
    key: "Macau",
    iso_code_3: "MAC",
  },
  {
    code: "MK",
    name_en: "MACEDONIA",
    dial_code: "+389",
    name_zh: "马其顿",
    key: "Macedonia",
    iso_code_3: "MKD",
  },
  {
    code: "MG",
    name_en: "MADAGASCAR",
    dial_code: "+261",
    name_zh: "马达加斯加",
    key: "Madagascar",
    iso_code_3: "MDG",
  },
  {
    code: "MW",
    name_en: "MALAWI",
    dial_code: "+265",
    name_zh: "马拉维",
    key: "Malawi",
    iso_code_3: "MWI",
  },
  {
    code: "MV",
    name_en: "MALDIVES",
    dial_code: "+960",
    name_zh: "马尔代夫",
    key: "Maldives",
    iso_code_3: "MDV",
  },
  {
    code: "ML",
    name_en: "MALI",
    dial_code: "+223",
    name_zh: "马里",
    key: "Mali",
    iso_code_3: "MLI",
  },
  {
    code: "MT",
    name_en: "MALTA",
    dial_code: "+356",
    name_zh: "马耳他",
    key: "Malta",
    iso_code_3: "MLT",
  },
  {
    code: "MH",
    name_en: "MARSHALL ISLANDS",
    dial_code: "+692",
    name_zh: "马绍尔群岛",
    key: "Marshall Islands",
    iso_code_3: "MHL",
  },
  {
    code: "MQ",
    name_en: "MARTINIQUE",
    dial_code: "+596",
    name_zh: "马提尼克",
    key: "Martinique",
    iso_code_3: "MTQ",
  },
  {
    code: "MR",
    name_en: "MAURITANIA",
    dial_code: "+222",
    name_zh: "毛里塔尼亚",
    key: "Mauritania",
    iso_code_3: "MRT",
  },
  {
    code: "MU",
    name_en: "MAURITIUS",
    dial_code: "+230",
    name_zh: "毛里求斯",
    key: "Mauritius",
    iso_code_3: "MUS",
  },
  {
    code: "YT",
    name_en: "MAYOTTE",
    dial_code: "+262",
    name_zh: "马约特",
    key: "Mayotte",
    iso_code_3: "MYT",
  },
  {
    code: "MX",
    name_en: "MEXICO",
    dial_code: "+52",
    name_zh: "墨西哥",
    key: "Mexico",
    iso_code_3: "MEX",
  },
  {
    code: "FM",
    name_en: "MICRONESIA",
    dial_code: "+691",
    name_zh: "密克罗尼西亚",
    key: "Micronesia",
    iso_code_3: "FSM",
  },
  {
    code: "MD",
    name_en: "MOLDOVA",
    dial_code: "+373",
    name_zh: "摩尔多瓦",
    key: "Moldova",
    iso_code_3: "MDA",
  },
  {
    code: "MC",
    name_en: "MONACO",
    dial_code: "+377",
    name_zh: "摩纳哥",
    key: "Monaco",
    iso_code_3: "MCO",
  },
  {
    code: "MN",
    name_en: "MONGOLIA",
    dial_code: "+976",
    name_zh: "蒙古",
    key: "Mongolia",
    iso_code_3: "MNG",
  },
  {
    code: "ME",
    name_en: "MONTENEGRO",
    dial_code: "+382",
    name_zh: "黑山",
    key: "Montenegro",
    iso_code_3: "MNE",
  },
  {
    code: "MS",
    name_en: "MONTSERRAT",
    dial_code: "+1664",
    name_zh: "蒙特塞拉特",
    key: "Montserrat",
    iso_code_3: "MSR",
  },
  {
    code: "MA",
    name_en: "MOROCCO",
    dial_code: "+212",
    name_zh: "摩洛哥",
    key: "Morocco",
    iso_code_3: "MAR",
  },
  {
    code: "MZ",
    name_en: "MOZAMBIQUE",
    dial_code: "+258",
    name_zh: "莫桑比克",
    key: "Mozambique",
    iso_code_3: "MOZ",
  },
  {
    code: "MM",
    name_en: "BURMA (REPUBLIC OF THE UNION OF MYANMAR)",
    dial_code: "+95",
    name_zh: "缅甸（缅甸联邦共和国）",
    key: "Burma (Republic of the Union of Myanmar)",
    iso_code_3: "MMR",
  },
  {
    code: "NA",
    name_en: "NAMIBIA",
    dial_code: "+264",
    name_zh: "纳米比亚",
    key: "Namibia",
    iso_code_3: "NAM",
  },
  {
    code: "NR",
    name_en: "NAURU",
    dial_code: "+674",
    name_zh: "瑙鲁",
    key: "Nauru",
    iso_code_3: "NRU",
  },
  {
    code: "NP",
    name_en: "NEPAL",
    dial_code: "+977",
    name_zh: "尼泊尔",
    key: "Nepal",
    iso_code_3: "NPL",
  },
  {
    code: "NL",
    name_en: "NETHERLANDS",
    dial_code: "+31",
    name_zh: "荷兰",
    key: "Netherlands",
    iso_code_3: "NLD",
  },
  {
    code: "NC",
    name_en: "NEW CALEDONIA",
    dial_code: "+687",
    name_zh: "新喀里多尼亚",
    key: "New Caledonia",
    iso_code_3: "NCL",
  },
  {
    code: "NZ",
    name_en: "NEW ZEALAND",
    dial_code: "+64",
    name_zh: "新西兰",
    key: "New Zealand",
    iso_code_3: "NZL",
  },
  {
    code: "NI",
    name_en: "NICARAGUA",
    dial_code: "+505",
    name_zh: "尼加拉瓜",
    key: "Nicaragua",
    iso_code_3: "NIC",
  },
  {
    code: "NE",
    name_en: "NIGER",
    dial_code: "+227",
    name_zh: "尼日尔",
    key: "Niger",
    iso_code_3: "NER",
  },
  {
    code: "NG",
    name_en: "NIGERIA",
    dial_code: "+234",
    name_zh: "尼日利亚",
    key: "Nigeria",
    iso_code_3: "NGA",
  },
  {
    code: "NU",
    name_en: "NIUE",
    dial_code: "+683",
    name_zh: "纽埃",
    key: "Niue",
    iso_code_3: "NIU",
  },
  {
    code: "NF",
    name_en: "NORFOLK ISLAND",
    dial_code: "+672",
    name_zh: "诺福克岛",
    key: "Norfolk Island",
    iso_code_3: "NFK",
  },
  {
    code: "MP",
    name_en: "NORTHERN MARIANA ISLANDS",
    dial_code: "+1670",
    name_zh: "北马里亚纳群岛",
    key: "Northern Mariana Islands",
    iso_code_3: "MNP",
  },
  {
    code: "NO",
    name_en: "NORWAY",
    dial_code: "+47",
    name_zh: "挪威",
    key: "Norway",
    iso_code_3: "NOR",
  },
  {
    code: "PS",
    name_en: "PALESTINE",
    dial_code: "+970",
    name_zh: "巴勒斯坦",
    key: "Palestine",
    iso_code_3: "PSE",
  },
  {
    code: "OM",
    name_en: "OMAN",
    dial_code: "+968",
    name_zh: "阿曼",
    key: "Oman",
    iso_code_3: "OMN",
  },
  {
    code: "PK",
    name_en: "PAKISTAN",
    dial_code: "+92",
    name_zh: "巴基斯坦",
    key: "Pakistan",
    iso_code_3: "PAK",
  },
  {
    code: "PW",
    name_en: "PALAU",
    dial_code: "+680",
    name_zh: "帕劳",
    key: "Palau",
    iso_code_3: "PLW",
  },
  {
    code: "PA",
    name_en: "PANAMA",
    dial_code: "+507",
    name_zh: "巴拿马",
    key: "Panama",
    iso_code_3: "PAN",
  },
  {
    code: "PG",
    name_en: "PAPUA NEW GUINEA",
    dial_code: "+675",
    name_zh: "巴布亚新几内亚",
    key: "Papua New Guinea",
    iso_code_3: "PNG",
  },
  {
    code: "PY",
    name_en: "PARAGUAY",
    dial_code: "+595",
    name_zh: "巴拉圭",
    key: "Paraguay",
    iso_code_3: "PRY",
  },
  {
    code: "PE",
    name_en: "PERU",
    dial_code: "+51",
    name_zh: "秘鲁",
    key: "Peru",
    iso_code_3: "PER",
  },
  {
    code: "PH",
    name_en: "PHILIPPINES",
    dial_code: "+63",
    name_zh: "菲律宾",
    key: "Philippines",
    iso_code_3: "PHL",
  },
  {
    code: "PN",
    name_en: "PITCAIRN",
    dial_code: "+870",
    name_zh: "皮特凯恩",
    key: "Pitcairn",
    iso_code_3: "PCN",
  },
  {
    code: "PL",
    name_en: "POLAND",
    dial_code: "+48",
    name_zh: "波兰",
    key: "Poland",
    iso_code_3: "POL",
  },
  {
    code: "PT",
    name_en: "PORTUGAL",
    dial_code: "+351",
    name_zh: "葡萄牙",
    key: "Portugal",
    iso_code_3: "PRT",
  },
  {
    code: "PR",
    name_en: "PUERTO RICO",
    dial_code: "+1939",
    name_zh: "波多黎各",
    key: "Puerto Rico",
    iso_code_3: "PRI",
  },
  {
    code: "QA",
    name_en: "QATAR",
    dial_code: "+974",
    name_zh: "卡塔尔",
    key: "Qatar",
    iso_code_3: "QAT",
  },
  {
    code: "RE",
    name_en: "REUNION",
    dial_code: "+262",
    name_zh: "留尼汪",
    key: "Reunion",
    iso_code_3: "REU",
  },
  {
    code: "RO",
    name_en: "ROMANIA",
    dial_code: "+40",
    name_zh: "罗马尼亚",
    key: "Romania",
    iso_code_3: "ROU",
  },
  {
    code: "RU",
    name_en: "RUSSIAN FEDERATION",
    dial_code: "+7",
    name_zh: "俄罗斯联邦",
    key: "Russian Federation",
    iso_code_3: "RUS",
  },
  {
    code: "RW",
    name_en: "RWANDA",
    dial_code: "+250",
    name_zh: "卢旺达",
    key: "Rwanda",
    iso_code_3: "RWA",
  },
  {
    code: "BL",
    name_en: "SAINT BARTHELEMY",
    dial_code: "+590",
    name_zh: "圣巴泰勒米",
    key: "Saint Barthelemy",
    iso_code_3: "BLM",
  },
  {
    code: "SH",
    name_en: "SAINT HELENA",
    dial_code: "+290",
    name_zh: "圣赫勒拿岛",
    key: "Saint Helena",
    iso_code_3: "SHN",
  },
  {
    code: "KN",
    name_en: "SAINT KITTS AND NEVIS",
    dial_code: "+1869",
    name_zh: "圣基茨和尼维斯",
    key: "Saint Kitts and Nevis",
    iso_code_3: "KNA",
  },
  {
    code: "LC",
    name_en: "SAINT LUCIA",
    dial_code: "+1758",
    name_zh: "圣卢西亚",
    key: "Saint Lucia",
    iso_code_3: "LCA",
  },
  {
    code: "MF",
    name_en: "SAINT MARTIN (FRANCE)",
    dial_code: "+590",
    name_zh: "圣马丁（法国）",
    key: "Saint Martin (France)",
    iso_code_3: "MAF",
  },
  {
    code: "PM",
    name_en: "SAINT PIERRE AND MIQUELON",
    dial_code: "+508",
    name_zh: "圣皮埃尔和密克隆",
    key: "Saint Pierre and Miquelon",
    iso_code_3: "SPM",
  },
  {
    code: "VC",
    name_en: "SAINT VINCENT AND GRENADINES",
    dial_code: "+1-784",
    name_zh: "圣文森特和格林纳丁斯",
    key: "Saint Vincent and Grenadines",
    iso_code_3: "VCT",
  },
  {
    code: "WS",
    name_en: "SAMOA",
    dial_code: "+685",
    name_zh: "萨摩亚",
    key: "Samoa",
  },
  {
    code: "SM",
    name_en: "SAN MARINO",
    dial_code: "+378",
    name_zh: "圣马力诺",
    key: "San Marino",
    iso_code_3: "SMR",
  },
  {
    code: "ST",
    name_en: "SAO TOME AND PRINCIPE",
    dial_code: "+239",
    name_zh: "圣多美和普林西比",
    key: "Sao Tome and Principe",
    iso_code_3: "STP",
  },
  {
    code: "SA",
    name_en: "SAUDI ARABIA",
    dial_code: "+966",
    name_zh: "沙特阿拉伯",
    key: "Saudi Arabia",
    iso_code_3: "SAU",
  },
  {
    code: "SN",
    name_en: "SENEGAL",
    dial_code: "+221",
    name_zh: "塞内加尔",
    key: "Senegal",
    iso_code_3: "SEN",
  },
  {
    code: "RS",
    name_en: "SERBIA",
    dial_code: "+381",
    name_zh: "塞尔维亚",
    key: "Serbia",
    iso_code_3: "SRB",
  },
  {
    code: "SC",
    name_en: "SEYCHELLES",
    dial_code: "+248",
    name_zh: "塞舌尔",
    key: "Seychelles",
    iso_code_3: "SYC",
  },
  {
    code: "SL",
    name_en: "SIERRA LEONE",
    dial_code: "+232",
    name_zh: "塞拉利昂",
    key: "Sierra Leone",
    iso_code_3: "SLE",
  },
  {
    code: "SX",
    name_en: "SAINT MARTIN (NETHERLANDS)",
    dial_code: "+1-721",
    name_zh: "圣马丁（荷兰）",
    key: "Saint Martin (Netherlands)",
    iso_code_3: "SXM",
  },
  {
    code: "SK",
    name_en: "SLOVAKIA",
    dial_code: "+421",
    name_zh: "斯洛伐克",
    key: "Slovakia",
    iso_code_3: "SVK",
  },
  {
    code: "SI",
    name_en: "SLOVENIA",
    dial_code: "+386",
    name_zh: "斯洛文尼亚",
    key: "Slovenia",
    iso_code_3: "SVN",
  },
  {
    code: "SB",
    name_en: "SOLOMON ISLANDS",
    dial_code: "+677",
    name_zh: "所罗门群岛",
    key: "Solomon Islands",
    iso_code_3: "SLB",
  },
  {
    code: "SO",
    name_en: "SOMALIA",
    dial_code: "+252",
    name_zh: "索马里",
    key: "Somalia",
    iso_code_3: "SOM",
  },
  {
    code: "ZA",
    name_en: "SOUTH AFRICA",
    dial_code: "+27",
    name_zh: "南非",
    key: "South Africa",
    iso_code_3: "ZAF",
  },
  {
    code: "GS",
    name_en: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
    dial_code: "+500",
    name_zh: "南乔治亚岛和南桑威奇群岛",
    key: "South Georgia and the South Sandwich Islands",
    iso_code_3: "SGS",
  },
  {
    code: "SS",
    name_en: "SOUTH SUDAN",
    dial_code: "+211",
    name_zh: "南苏丹",
    key: "South Sudan",
    iso_code_3: "SSD",
  },
  {
    code: "ES",
    name_en: "SPAIN",
    dial_code: "+34",
    name_zh: "西班牙",
    key: "Spain",
    iso_code_3: "ESP",
  },
  {
    code: "LK",
    name_en: "SRI LANKA",
    dial_code: "+94",
    name_zh: "斯里兰卡",
    key: "Sri Lanka",
    iso_code_3: "LKA",
  },
  {
    code: "SD",
    name_en: "SUDAN",
    dial_code: "+249",
    name_zh: "苏丹",
    key: "Sudan",
    iso_code_3: "SDN",
  },
  {
    code: "SR",
    name_en: "SURINAME",
    dial_code: "+597",
    name_zh: "苏里南",
    key: "Suriname",
    iso_code_3: "SUR",
  },
  {
    code: "SJ",
    name_en: "SVALBARD AND JAN MAYEN ISLANDS",
    dial_code: "+47",
    name_zh: "斯瓦尔巴群岛和扬马延岛",
    key: "Svalbard and Jan Mayen Islands",
    iso_code_3: "SJM",
  },
  {
    code: "SZ",
    name_en: "SWAZILAND",
    dial_code: "+268",
    name_zh: "斯威士兰",
    key: "Swaziland",
    iso_code_3: "SWZ",
  },
  {
    code: "SE",
    name_en: "SWEDEN",
    dial_code: "+46",
    name_zh: "瑞典",
    key: "Sweden",
    iso_code_3: "SWE",
  },
  {
    code: "CH",
    name_en: "SWITZERLAND",
    dial_code: "+41",
    name_zh: "瑞士",
    key: "Switzerland",
    iso_code_3: "CHE",
  },
  {
    code: "SY",
    name_en: "SYRIA",
    dial_code: "+963",
    name_zh: "叙利亚",
    key: "Syria",
    iso_code_3: "SYR",
  },
  {
    code: "TW",
    name_en: "TAIWAN",
    dial_code: "+886",
    name_zh: "台湾",
    key: "Taiwan",
    iso_code_3: "TWN",
  },
  {
    code: "TJ",
    name_en: "TAJIKISTAN",
    dial_code: "+992",
    name_zh: "塔吉克斯坦",
    key: "Tajikistan",
    iso_code_3: "TJK",
  },
  {
    code: "TZ",
    name_en: "TANZANIA",
    dial_code: "+255",
    name_zh: "坦桑尼亚",
    key: "Tanzania",
    iso_code_3: "TZA",
  },
  {
    code: "TH",
    name_en: "THAILAND",
    dial_code: "+66",
    name_zh: "泰国",
    key: "Thailand",
    iso_code_3: "THA",
  },
  {
    code: "TL",
    name_en: "TIMOR-LESTE",
    dial_code: "+670",
    name_zh: "东帝汶",
    key: "Timor-Leste",
    iso_code_3: "TLS",
  },
  {
    code: "TG",
    name_en: "TOGO",
    dial_code: "+228",
    name_zh: "多哥",
    key: "Togo",
    iso_code_3: "TGO",
  },
  {
    code: "TK",
    name_en: "TOKELAU",
    dial_code: "+690",
    name_zh: "托克劳",
    key: "Tokelau",
    iso_code_3: "TKL",
  },
  {
    code: "TO",
    name_en: "TONGA",
    dial_code: "+676",
    name_zh: "汤加",
    key: "Tonga",
    iso_code_3: "TON",
  },
  {
    code: "TT",
    name_en: "TRINIDAD AND TOBAGO",
    dial_code: "+1868",
    name_zh: "特立尼达和多巴哥",
    key: "Trinidad and Tobago",
    iso_code_3: "TTO",
  },
  {
    code: "TN",
    name_en: "TUNISIA",
    dial_code: "+216",
    name_zh: "突尼斯",
    key: "Tunisia",
    iso_code_3: "TUN",
  },
  {
    code: "TR",
    name_en: "TURKEY",
    dial_code: "+90",
    name_zh: "土耳其",
    key: "Turkey",
    iso_code_3: "TUR",
  },
  {
    code: "TM",
    name_en: "TURKMENISTAN",
    dial_code: "+993",
    name_zh: "土库曼斯坦",
    key: "Turkmenistan",
    iso_code_3: "TKM",
  },
  {
    code: "TC",
    name_en: "TURKS AND CAICOS ISLANDS",
    dial_code: "+1649",
    name_zh: "特克斯和凯科斯群岛",
    key: "Turks and Caicos Islands",
    iso_code_3: "TCA",
  },
  {
    code: "TV",
    name_en: "TUVALU",
    dial_code: "+688",
    name_zh: "图瓦卢",
    key: "Tuvalu",
    iso_code_3: "TUV",
  },
  {
    code: "UG",
    name_en: "UGANDA",
    dial_code: "+256",
    name_zh: "乌干达",
    key: "Uganda",
    iso_code_3: "UGA",
  },
  {
    code: "UA",
    name_en: "UKRAINE",
    dial_code: "+380",
    name_zh: "乌克兰",
    key: "Ukraine",
    iso_code_3: "UKR",
  },
  {
    code: "AE",
    name_en: "UNITED ARAB EMIRATES",
    dial_code: "+971",
    name_zh: "阿拉伯联合酋长国",
    key: "United Arab Emirates",
    iso_code_3: "ARE",
  },
  {
    code: "UY",
    name_en: "URUGUAY",
    dial_code: "+598",
    name_zh: "乌拉圭",
    key: "Uruguay",
    iso_code_3: "URY",
  },
  {
    code: "UZ",
    name_en: "UZBEKISTAN",
    dial_code: "+998",
    name_zh: "乌兹别克斯坦",
    key: "Uzbekistan",
    iso_code_3: "UZB",
  },
  {
    code: "VU",
    name_en: "VANUATU",
    dial_code: "+678",
    name_zh: "瓦努阿图",
    key: "Vanuatu",
    iso_code_3: "VUT",
  },
  {
    code: "VE",
    name_en: "VENEZUELA",
    dial_code: "+58",
    name_zh: "委内瑞拉",
    key: "Venezuela",
    iso_code_3: "VEN",
  },
  {
    code: "VN",
    name_en: "VIETNAM",
    dial_code: "+84",
    name_zh: "越南",
    key: "Vietnam",
    iso_code_3: "VNM",
  },
  {
    code: "VG",
    name_en: "BRITISH VIRGIN ISLANDS",
    dial_code: "+1284",
    name_zh: "英属维尔京群岛",
    key: "British Virgin Islands",
    iso_code_3: "VGB",
  },
  {
    code: "VI",
    name_en: "UNITED STATES VIRGIN ISLANDS",
    dial_code: "+1340",
    name_zh: "美属维尔京群岛",
    key: "United States Virgin Islands",
    iso_code_3: "VIR",
  },
  {
    code: "WF",
    name_en: "WALLIS AND FUTUNA ISLANDS",
    dial_code: "+681",
    name_zh: "瓦利斯群岛和富图纳群岛",
    key: "Wallis and Futuna Islands",
    iso_code_3: "WLF",
  },
  {
    code: "EH",
    name_en: "WESTERN SAHARA",
    dial_code: "+212",
    name_zh: "撒哈拉沙漠西部",
    key: "Western Sahara",
    iso_code_3: "ESH",
  },
  {
    code: "YE",
    name_en: "YEMEN",
    dial_code: "+967",
    name_zh: "也门",
    key: "Yemen",
    iso_code_3: "YEM",
  },
  {
    code: "ZM",
    name_en: "ZAMBIA",
    dial_code: "+260",
    name_zh: "赞比亚",
    key: "Zambia",
    iso_code_3: "ZMB",
  },
  {
    code: "ZW",
    name_en: "ZIMBABWE",
    dial_code: "+263",
    name_zh: "津巴布韦",
    key: "Zimbabwe",
    iso_code_3: "ZWE",
  },
  {
    code: "AC",
    name_en: "ASCENSION",
    dial_code: "+247",
    name_zh: "阿森松岛",
    key: "Ascension",
  },
  {
    code: "UM",
    name_en: "BAKER ISLAND",
    dial_code: "+246",
    name_zh: "贝克岛",
    key: "Baker Island",
    iso_code_3: "UMI",
  },
  {
    code: "TF",
    name_en: "FRENCH SOUTHERN AND ANTARCTIC LANDS",
    dial_code: "+262",
    name_zh: "法属南部和南极土地",
    key: "French Southern and Antarctic Lands",
    iso_code_3: "ATF",
  },
  {
    code: "XK",
    name_en: "KOSOVO",
    dial_code: "+383",
    name_zh: "科索沃",
    key: "Kosovo",
    iso_code_3: "XK",
  },
  {
    code: "TCX",
    name_en: "TRISTAN DA CUNHA",
    dial_code: "+",
    name_zh: "特里斯坦达库尼亚",
    key: "Tristan da Cunha",
    iso_code_3: "TCX",
  },
  {
    code: "CMF",
    name_en: "WAKE ISLAND",
    dial_code: "+",
    name_zh: "威克岛",
    key: "Wake Island",
    iso_code_3: "CMF",
  },
  {
    code: "AN",
    name_en: "NETHERLANDS ANTILLES",
    dial_code: "+599",
    name_zh: "荷属安的列斯",
    key: "Netherlands Antilles",
    iso_code_3: "AN",
  },
  {
    code: "--",
    name_en: "UNKNOWN",
    dial_code: "+",
    name_zh: "未知",
    key: "UNKNOWN",
    iso_code_3: "---",
  },
])



export default Countries;
